### ISSUE TITLE
Windows Usage

### ISSUE THREAD

**Issue by sadeghbarati** [webfansplz/vite-plugin-vue-inspector#11]
How to use this vite plugin in windows OS ?

I tried both ways

1. command line set [env](https://github.com/sindresorhus/guides/blob/main/set-environment-variables.md)
2. `Edit the system environment variables`

---

![Screenshot (120)](https://user-images.githubusercontent.com/17789047/162560038-0a46c6fd-d4a4-4a6e-bc6e-e5d9fc498810.png)

---

`defaultEditor` option in vite would be so helpfull instead of setting env

```js
Inspector({
    enabled: true,
    defaultEditor: 'code'
})
```

Thanks

**Comment by sadeghbarati** [comment]
`data-inspector-file` attribute is present in devtools but,

nothing happened when you clicked the element and no tooltip appears

**Comment by webfansplz** [comment]
![AC095219-5338-4D72-9695-54476E27BBE9](https://user-images.githubusercontent.com/22515951/162560523-9347af48-89f7-4468-8fc1-c4c33693237d.png)

**Comment by sadeghbarati** [comment]
https://stackoverflow.com/questions/47528373/visual-studio-code-shell-command-install-code-command-in-path-command

it's already installed by default

**Comment by ffrechina** [comment]
not working onwindows at all

**Comment by webfansplz** [comment]
> not working onwindows at all

Is it also the issue of can’t open the editor ?

**Comment by ffrechina** [comment]
> > not working onwindows at all
> 
> Is it also the issue of can’t open the editor ?
> 
> You can Follow the [configuration-ide docs](https://github.com/webfansplz/vite-plugin-vue-inspector#--configuration-ide--editor) and ensure that the configuration is correct.

of course I did it but unfortunately not working at all

**Comment by SamVerschueren** [comment]
@ffrechina Could you execute the following commands and copy-paste the output of both of them?

```sh
wmic process where \"executablepath is not null\" get executablepath
```

```sh
powershell -Command "Get-Process | Select-Object Path"
```

I noticed that this plugin uses a different command than [the one used by `launch-editor`](https://github.com/yyx990803/launch-editor/blob/master/packages/launch-editor/guess.js#L31). And I'm wondering if that makes a difference.

**Comment by ffrechina** [comment]
@SamVerschueren for the first command I get an error about not valid query. For the second, I get a lot of paths not related to this topic. Could you please be more specific of what do you need?

**Comment by SamVerschueren** [comment]
Can you open VSCode (or the editor you use), run that `powershell` command and then look for any path that ends with one of the following editors?

```
Brackets.exe
Code.exe
atom.exe
sublime_text.exe
notepad++.exe
clion.exe
clion64.exe
idea.exe
idea64.exe
phpstorm.exe
phpstorm64.exe
pycharm.exe
pycharm64.exe
rubymine.exe
rubymine64.exe
webstorm.exe
webstorm64.exe
```

That command just dumps all the paths of the exe's of the process. The `launch-editor` package then looks through the entire list trying to match it with one of the above executables. If it finds `sublime_text.exe`, it knows you are working with Sublime and knows how to open that editor correctly.

**Comment by ffrechina** [comment]
it dumps both Code.exe and sublime_text.exe

**Comment by SamVerschueren** [comment]
@webfansplz Any reason you use the `wmic` command instead of the `PowerShell` one? It looks like the code in this package is based on [launch-editor/guess.js](https://github.com/yyx990803/launch-editor/blob/master/packages/launch-editor/guess.js) which uses `powershell` and seems to work for @ffrechina.

**Comment by webfansplz** [comment]
> @webfansplz Any reason you use the `wmic` command instead of the `PowerShell` one? It looks like the code in this package is based on [launch-editor/guess.js](https://github.com/yyx990803/launch-editor/blob/master/packages/launch-editor/guess.js) which uses `powershell` and seems to work for @ffrechina.

https://github.com/webfansplz/vite-plugin-vue-inspector/blob/8327428abb6280fb976e1df8d64eb28c66392f7d/src/launch-editor.ts#L2

It's fork from `create-react-app`, i'll use `powershell` instead of `wmic` .

**Comment by webfansplz** [comment]
@ffrechina Update to v1.0.1 and try again.

**Comment by webfansplz** [comment]
@SamVerschueren Thanks for your suggestion. ♥️

**Comment by SamVerschueren** [comment]
Awesome, hope this is fixed now ❤️ !

**Comment by ffrechina** [comment]
it works perfectly! 
thank you so much guys! ❤️
