### ISSUE TITLE
最新版windows系统无法使用

### ISSUE THREAD

**Issue by BonjourBernard** [webfansplz/vite-plugin-vue-inspector#12]
vue2  windows系统使用3.0.0版本的没效果
0.2.6版本可以使用

看了下属性和交互代码注入到页面了 但是没出来悬浮框 点击也没效果

**Comment by webfansplz** [comment]
vite版本是多少哈

**Comment by BonjourBernard** [comment]
vue版本 2.6.11
vite版本 2.8.6 
我得先搬砖 
![3345f1f4-d236-4537-9422-c50ae755236c](https://user-images.githubusercontent.com/16251689/163503051-b0a9d00e-4d3f-4d29-aada-edec456b3a6f.png)

**Comment by webfansplz** [comment]
可以升级`Vite`到`2.9.x` 看看

**Comment by webfansplz** [comment]
可以试试 V1.0.1版本,如果有问题再重新打开Issue.
