### ISSUE TITLE
Not working on Nuxt.rc 12 - 13

### ISSUE THREAD

**Issue by sondh0127** [webfansplz/vite-plugin-vue-inspector#29]
Reproduction: https://github.com/sondh0127/nuxt-app
![image](https://user-images.githubusercontent.com/62163604/200741583-82b63fa2-976f-4da3-8013-3709ef3691c8.png)

**Comment by jjaimealeman** [comment]
Yup, can also confirm it is **not** working for `"nuxt": "3.0.0-rc.12",` 😥

**Comment by webfansplz** [comment]
Fixed in `v1.1.4`
