### ISSUE TITLE
When I use the '?raw' suffix to get the strings, the program reports an error.

### ISSUE THREAD

**Issue by tjstyx** [webfansplz/vite-plugin-vue-inspector#33]
[mini repo](https://stackblitz.com/edit/inspector-mini-repo?file=src%2FApp.vue)

![image](https://user-images.githubusercontent.com/49975960/207762009-9091452a-cb53-45d1-a34e-cfb8b1305530.png)

**Comment by webfansplz** [comment]
Thanks for your feedback.Fixed in v2.0.2
