### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by hooray** [webfansplz/vite-plugin-vue-inspector#34]
I created an empty project using `pnpm create vite` and then installed `vite-plugin-vue-inspector` and found that HMR doesn't work.

**Comment by webfansplz** [comment]
Seems a Vite issue. Vite v4.0.0 works fine, but broken in v4.0.1.

**Comment by hooray** [comment]
OK, then wait for Vite to fix it.

**Comment by dvjeshka** [comment]
HMR is not working for me with v4.0.0 and v4.0.1

**Comment by webfansplz** [comment]
Fixed in V2.0.3
