### ISSUE TITLE
所有文件有下划线的都无法打开

### ISSUE THREAD

**Issue by sail-sail** [webfansplz/vite-plugin-vue-inspector#38]
比如: /#/scrm/setting/sales_workflow 网络会发送成
/__open-stack-frame-in-editor?file=src\views\scrm\setting\sales&line=workflow\List.vue&column=24
很明显, 下划线的截取除了问题, sales_workflow 这个单词被 _ 下划线 截断了

**Comment by webfansplz** [comment]
Thanks for your feedback, fixed in v3.0.3.
