### ISSUE TITLE
vite+vue3项目不生效

### ISSUE THREAD

**Issue by wforguo** [webfansplz/vite-plugin-vue-inspector#55]
vite+vue3项目不生效

**Comment by webfansplz** [comment]
可以提供一个最小复现Demo吗

**Comment by wforguo** [comment]
最小demo

https://github.com/wforguo/vite-inspector

打开的请求是发起的，但是编辑器并没有调起

![image](https://user-images.githubusercontent.com/23009078/224468645-b23f3704-b472-4ea8-8363-2d756f6d044e.png)

<img width="713" alt="image" src="https://user-images.githubusercontent.com/23009078/224468630-84d06d34-f993-401a-8d4f-df0c4d54981a.png">

麻烦看下，谢谢

**Comment by wforguo** [comment]
> 最小demo
> 
> https://github.com/wforguo/vite-inspector
> 
> 打开的请求是发起的，但是编辑器并没有调起
> 
> ![image](https://user-images.githubusercontent.com/23009078/224468645-b23f3704-b472-4ea8-8363-2d756f6d044e.png)
> 
> <img alt="image" width="713" src="https://user-images.githubusercontent.com/23009078/224468630-84d06d34-f993-401a-8d4f-df0c4d54981a.png">
> 
> 麻烦看下，谢谢

@webfansplz webfansplz

**Comment by wforguo** [comment]
webstorm编辑器

**Comment by webfansplz** [comment]
https://github.com/webfansplz/vite-plugin-vue-inspector#--configuration-ide--editor 可以看下编辑器相关配置是否正确

**Comment by wforguo** [comment]
> https://github.com/webfansplz/vite-plugin-vue-inspector#--configuration-ide--editor 可以看下编辑器相关配置是否正确

可以了谢谢，我的webstorm版本带了时间，去掉就可以了 WebStorm.2021.03--> webstorm
