### ISSUE TITLE
Disable button

### ISSUE THREAD

**Issue by dajpes** [webfansplz/vite-plugin-vue-inspector#7]
Hey!

Is there a way to disable the button functionality by default, everytime I refresh the page, the button is enable so I have to manually disable it so I can interact with my app

**Comment by webfansplz** [comment]
I‘ll add an initial enabled state option to support it.

**Comment by webfansplz** [comment]
V0.2.5 has already supported . 

```ts
// vite.config.ts

import { defineConfig } from "vite"
import Vue from "@vitejs/plugin-vue"
import VueJsx from "@vitejs/plugin-vue-jsx"
import Inspector from "vite-plugin-vue-inspector"

export default defineConfig({
  plugins: [Vue(), VueJsx(), Inspector({ enabled: false })],
})


```

**Comment by mzaini30** [comment]
> V0.2.5 has already supported .
> 
> ```ts
> // vite.config.ts
> 
> import { defineConfig } from "vite"
> import Vue from "@vitejs/plugin-vue"
> import VueJsx from "@vitejs/plugin-vue-jsx"
> import Inspector from "vite-plugin-vue-inspector"
> 
> export default defineConfig({
>   plugins: [Vue(), VueJsx(), Inspector({ enabled: false })],
> })
> ```

it's very helpful if you add it in docs. Thanks...

**Comment by webfansplz** [comment]
> > V0.2.5 has already supported .
> > ```ts
> > // vite.config.ts
> > 
> > import { defineConfig } from "vite"
> > import Vue from "@vitejs/plugin-vue"
> > import VueJsx from "@vitejs/plugin-vue-jsx"
> > import Inspector from "vite-plugin-vue-inspector"
> > 
> > export default defineConfig({
> >   plugins: [Vue(), VueJsx(), Inspector({ enabled: false })],
> > })
> > ```
> 
> it's very helpful if you add it in docs. Thanks...



Thanks for your feedback, updated. https://github.com/webfansplz/vite-plugin-vue-inspector#options
