### ISSUE TITLE
some suggestion

### ISSUE THREAD

**Issue by a145789** [webfansplz/vite-plugin-vue-inspector#8]
I've been using it for a while and have some experience suggestions

1. The operation button is too big, please make it smaller. It would be better to have a little transparency in disabled state
2. The image used for the button is from Github, but sometimes the connection is not smooth, so it cannot be loaded

Thanks for developing this plugin

**Comment by webfansplz** [comment]
Thank you for your feedback.

1. I would rethink the design of it.

2. It has users from all over the world and I don't have a CDN server. I've tried Base64, but it's clunky. I'll reevaluate that. Thank you.
